// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"fmt"
	"io"
	"strconv"
)

type Order struct {
	Name    string    `json:"name"`
	Runtime *Runtime  `json:"runtime"`
	Path    *string   `json:"path"`
	Env     []*string `json:"env"`
}

type Shop struct {
	Name     string     `json:"name"`
	Host     string     `json:"host"`
	Runtimes []*Runtime `json:"runtimes"`
	Port     *int       `json:"port"`
}

type Runtime string

const (
	RuntimeNode14 Runtime = "node14"
	RuntimeNode16 Runtime = "node16"
	RuntimeGo1_15 Runtime = "go1_15"
	RuntimeGo1_17 Runtime = "go1_17"
)

var AllRuntime = []Runtime{
	RuntimeNode14,
	RuntimeNode16,
	RuntimeGo1_15,
	RuntimeGo1_17,
}

func (e Runtime) IsValid() bool {
	switch e {
	case RuntimeNode14, RuntimeNode16, RuntimeGo1_15, RuntimeGo1_17:
		return true
	}
	return false
}

func (e Runtime) String() string {
	return string(e)
}

func (e *Runtime) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Runtime(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Runtime", str)
	}
	return nil
}

func (e Runtime) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
